# Generated by Django 5.0.4 on 2024-04-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicereqs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='location',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='Locaton',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
