# Generated by Django 5.0.4 on 2024-04-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicereqs', '0002_remove_servicerequest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='Locaton',
            field=models.CharField(max_length=20),
        ),
    ]
