# Generated by Django 5.0.4 on 2024-04-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicereqs', '0003_alter_servicerequest_locaton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='Locaton',
        ),
    ]
