# Generated by Django 5.0.4 on 2024-04-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicereqs', '0004_remove_servicerequest_locaton'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='Location',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
