# Generated by Django 5.0.4 on 2024-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicereqs', '0005_servicerequest_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='Location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
