# Generated by Django 5.0.4 on 2024-04-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicereqs', '0006_alter_servicerequest_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='employee',
            new_name='name',
        ),
    ]
