# Generated by Django 5.0.4 on 2024-04-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicereqs', '0008_rename_name_servicerequest_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
