# Generated by Django 4.2.11 on 2024-04-03 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('SAC', 'SAC'), ('Engineering', 'Engineering'), ('SAP_SD', 'SAP_SD'), ('SAP_PP', 'SAP_PP'), ('SAP_MM', 'SAP_MM'), ('SAP_FICO', 'SAP_FICO'), ('SAP_ABAP', 'SAP_ABAP')], max_length=20)),
                ('role', models.CharField(choices=[('Trainee', 'Trainee'), ('Associate', 'Associate'), ('Consultant', 'Consultant'), ('Senior Associate', 'Senior Associate'), ('Manager', 'Manager')], max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
