# Generated by Django 5.0.4 on 2024-04-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_position_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
