# Generated by Django 4.2.11 on 2024-04-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('REGISTERD', 'REGISTERD'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=50),
        ),
    ]
