# Generated by Django 4.2.11 on 2024-04-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=200)),
                ('Work', models.TextField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('date', models.DateField()),
                ('execution_type', models.CharField(choices=[('ONSITE', 'ONSITE'), ('OFFSITE', 'OFFSITE')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
