# Generated by Django 4.2.11 on 2024-04-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('EARNED_LEAVE', 'EARNED_LEAVE'), ('CASUAL_LEAVE', 'CASUAL_LEAVE'), ('SICK_LEAVE', 'SICK_LEAVE')], max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(choices=[('REGISTER', 'REGISTER'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=50)),
            ],
        ),
    ]
