# Generated by Django 5.0.4 on 2024-04-04 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        ('profiles', '0002_remove_profile_position_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
