# Generated by Django 5.0.4 on 2024-04-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leave_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
    ]
