# Generated by Django 4.2.11 on 2024-04-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('issuedate', models.DateTimeField()),
                ('duedate', models.DateTimeField()),
                ('status', models.CharField(choices=[('REGISTER', 'REGISTER'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=50)),
                ('priority_choices', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('SHOW_STOPPER', 'SHOW_STOPPER')], max_length=50)),
                ('module', models.CharField(choices=[('SAP SD', 'SAP SD'), ('SAP PP', 'SAP PP'), ('SAP MM', 'SAP MM'), ('SAP FICO', 'SAP FICO'), ('SAP ABAP', 'SAP ABAP')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
